version: '3.5'

services:
  bot:
    image: "${BOT_IMAGE_NAME}"
    container_name: "${BOT_CONTAINER_NAME}"
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
    - .:/usr/src/app/${BOT_NAME}
    command: python3 -m bot
    depends_on:
      - db
    env_file:
      - ".env"
    networks:
      - botnet
    restart: unless-stopped

  db:
    container_name: postgres
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASS}
      - POSTGRESQL_DATABASE=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - /var/postgredata/:/bitnami/postgresqlv
    networks:
      - botnet
    restart: unless-stopped

networks:
  botnet:
   driver: bridge


