"""analytic bonus

Revision ID: 535abab071d0
Revises: 6cd6a3d2fcfb
Create Date: 2021-11-17 02:04:19.264152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535abab071d0'
down_revision = '6cd6a3d2fcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Analytics', sa.Column('bonus', sa.Integer(), nullable=True))
    op.add_column('Analytics', sa.Column('bonuscount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Analytics', 'bonuscount')
    op.drop_column('Analytics', 'bonus')
    # ### end Alembic commands ###
