"""add description to Analytic table

Revision ID: 6cd6a3d2fcfb
Revises: 9c0e28cc2d2a
Create Date: 2021-11-16 01:54:12.755424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd6a3d2fcfb'
down_revision = '9c0e28cc2d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Analytics', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Analytics', 'description')
    # ### end Alembic commands ###
