"""add averaging to predict

Revision ID: 82008f29fbae
Revises: b337766180c8
Create Date: 2022-02-28 04:01:06.486181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82008f29fbae'
down_revision = 'b337766180c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Predicts_averaging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('predicted_date', sa.DateTime(), nullable=False),
    sa.Column('start_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('averaging_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('predicted_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stop_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('message_url', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['Predicts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Users', 'is_private_group_member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_private_group_member', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('Predicts_averaging')
    # ### end Alembic commands ###
