"""add stop_value and stopped columns to predict

Revision ID: 908d2ae759ec
Revises: d728fb5b8e5d
Create Date: 2022-01-24 01:13:58.187769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908d2ae759ec'
down_revision = 'd728fb5b8e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Predicts', sa.Column('stop_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('Predicts', sa.Column('stopped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Predicts', 'stopped')
    op.drop_column('Predicts', 'stop_value')
    # ### end Alembic commands ###
