"""add predicts_comment table

Revision ID: aa23a1c23f5c
Revises: afa1b71c1422
Create Date: 2021-12-17 09:56:41.161026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa23a1c23f5c'
down_revision = 'afa1b71c1422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Predicts_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.String(length=4000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('message_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['Predicts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Predicts_comments')
    # ### end Alembic commands ###
