"""add comment to predicts

Revision ID: afa1b71c1422
Revises: c3ef3849e1b0
Create Date: 2021-12-16 00:03:17.177372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa1b71c1422'
down_revision = 'c3ef3849e1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Predicts', sa.Column('comment', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Predicts', 'comment')
    # ### end Alembic commands ###
