"""add is_private_group_member column to users
Revision ID: b337766180c8
Revises: 908d2ae759ec
Create Date: 2022-02-07 01:47:27.172092
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b337766180c8'
down_revision = '908d2ae759ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_private_group_member', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_private_group_member')
    # ### end Alembic commands ###