"""Initial

Revision ID: b60a9ac811d3
Revises: 
Create Date: 2021-10-08 14:43:04.989662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60a9ac811d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Analytics',
    sa.Column('Nickname', sa.String(length=100), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('predicts_total', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('Users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('subscription_until', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('Predicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('figi', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('predicted_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('predicted_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('end_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('analytic_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['analytic_id'], ['Analytics.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Predicts')
    op.drop_table('Users')
    op.drop_table('Analytics')
    # ### end Alembic commands ###
