"""add message info

Revision ID: c3ef3849e1b0
Revises: 535abab071d0
Create Date: 2021-12-09 04:10:19.758158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ef3849e1b0'
down_revision = '535abab071d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Predicts', sa.Column('message_id', sa.BigInteger(), nullable=True))
    op.add_column('Predicts', sa.Column('message_url', sa.String(length=100), nullable=True))
    op.add_column('Predicts', sa.Column('message_text', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Predicts', 'message_text')
    op.drop_column('Predicts', 'message_url')
    op.drop_column('Predicts', 'message_id')
    # ### end Alembic commands ###
