"""risk_level

Revision ID: d728fb5b8e5d
Revises: 6575801cb7a6
Create Date: 2022-01-18 01:09:14.063390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd728fb5b8e5d'
down_revision = '6575801cb7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Predicts', sa.Column('risk_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Predicts', 'risk_level')
    # ### end Alembic commands ###
